{
 "title": "Win Stats of Lilya's Laptop",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "query": "http://192.168.50.161:8080" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_value{host=\"$host\", hardwareName=\"13th Gen Intel Core i7-13650HX\", hardwareType=\"CPU\", sensorType=\"Load\", sensorName=\"CPU Core Max\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "CPU Clock",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sensor_value{host=\"$host\", hardwareName=\"13th Gen Intel Core i7-13650HX\", hardwareType=\"CPU\", sensorType=\"Clock\", sensorName!=\"Bus Speed\"})",
     "legendFormat": "Avg Clock"
    }
   ]
  },
  {
   "title": "CPU Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_value{host=\"$host\", hardwareType=\"CPU\", hardwareName=\"13th Gen Intel Core i7-13650HX\", sensorType=\"Power\", sensorName=\"CPU Package\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_value{host=\"$host\", hardwareName=\"13th Gen Intel Core i7-13650HX\", hardwareType=\"CPU\", sensorType=\"Temperature\", sensorName=\"CPU Package\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_value{host=\"$host\", hardwareType=\"GPU\", hardwareName=\"NVIDIA GeForce RTX 4060 Laptop GPU\", sensorType=\"Load\", sensorName=\"GPU Core\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "GPU Clock",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_value{host=\"$host\", hardwareType=\"GPU\", hardwareName=\"NVIDIA GeForce RTX 4060 Laptop GPU\", sensorType=\"Clock\", sensorName=\"GPU Core\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_value{host=\"$host\", hardwareType=\"GPU\", hardwareName=\"NVIDIA GeForce RTX 4060 Laptop GPU\", sensorType=\"Power\", sensorName=\"GPU Package\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_value{host=\"$host\", hardwareType=\"GPU\", hardwareName=\"NVIDIA GeForce RTX 4060 Laptop GPU\", sensorType=\"Temperature\", sensorName=\"GPU Core\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "CPU/GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sensor_value{host=\"$host\", hardwareType=\"CPU\", sensorType=\"Temperature\", hardwareName=\"13th Gen Intel Core i7-13650HX\", sensorName=\"CPU Package\"}",
     "legendFormat": "CPU {{sensorName}}"
    },
    {
     "expr": "sensor_value{host=\"$host\", hardwareType=\"GPU\", sensorType=\"Temperature\", hardwareName=\"NVIDIA GeForce RTX 4060 Laptop GPU\"}",
     "legendFormat": "GPU {{sensorName}}"
    }
   ]
  },
  {
   "title": "CPU/GPU Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sensor_value{host=\"$host\", hardwareType=\"CPU\", sensorType=\"Power\", hardwareName=\"13th Gen Intel Core i7-13650HX\", sensorName=\"CPU Package\"}",
     "legendFormat": "CPU {{sensorName}}"
    },
    {
     "expr": "sensor_value{host=\"$host\", hardwareType=\"GPU\", sensorType=\"Power\", hardwareName=\"NVIDIA GeForce RTX 4060 Laptop GPU\", sensorName=\"GPU Package\"}",
     "legendFormat": "{{sensorName}}"
    },
    {
     "expr": "sum(sensor_value{host=\"$host\", hardwareType=\"CPU\", sensorType=\"Power\", hardwareName=\"13th Gen Intel Core i7-13650HX\", sensorName=\"CPU Package\"}) + sum(sensor_value{host=\"$host\", hardwareType=\"GPU\", sensorType=\"Power\", hardwareName=\"NVIDIA GeForce RTX 4060 Laptop GPU\", sensorName=\"GPU Package\"})",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}