{
 "title": "Win Stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sensor_value{hardwareType=\"CPU\", sensorType=\"Load\"})/7",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "CPU Clock",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sensor_value{hardwareType=\"CPU\", sensorType=\"Clock\", sensorName!=\"Bus Speed (/intelcpu/0/clock/0)\"})",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "CPU Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"CPU\", sensorType=\"Power\", sensorName=\"CPU Package (/intelcpu/0/power/0)\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sensor_value{hardwareType=\"CPU\", sensorType=\"Temperature\"})/7",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"GPU\", sensorType=\"Load\", sensorName=\"GPU Core (/nvidiagpu/0/load/0)\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "GPU Clock",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"GPU\", sensorType=\"Clock\", sensorName=\"GPU Core (/nvidiagpu/0/clock/0)\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"GPU\", sensorType=\"Power\", sensorName=\"GPU Power (/nvidiagpu/0/power/0)\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"GPU\", sensorType=\"Temperature\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "CPU/GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"CPU\", sensorType=\"Temperature\", sensorName=\"CPU Package (/intelcpu/0/temperature/6)\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "sensor_value{hardwareType=\"GPU\", sensorType=\"Temperature\"}",
     "legendFormat": "GPU"
    }
   ]
  },
  {
   "title": "CPU/GPU Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"CPU\", sensorType=\"Power\", sensorName=\"CPU Package (/intelcpu/0/power/0)\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "sensor_value{hardwareType=\"GPU\", sensorType=\"Power\"}",
     "legendFormat": "GPU"
    },
    {
     "expr": "sum(sensor_value{hardwareType=\"CPU\", sensorType=\"Power\", sensorName=\"CPU Package (/intelcpu/0/power/0)\"})+sum(sensor_value{hardwareType=\"GPU\", sensorType=\"Power\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "CPU Intel Core i7-9750H", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"CPU\", sensorType=\"Load\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"CPU\", sensorType=\"Temperature\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"CPU\", sensorType=\"Clock\", sensorName!=\"Bus Speed (/intelcpu/0/clock/0)\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"CPU\", sensorType=\"Power\", sensorName=\"CPU Package (/intelcpu/0/power/0)\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "GPU NVIDIA NVIDIA GeForce RTX 2060",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"GPU\", sensorType=\"Load\", sensorName!=\"GPU Memory (/nvidiagpu/0/load/4)\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"GPU\", sensorType=\"Temperature\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"GPU\", sensorType=\"Power\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "Clock",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"GPU\", sensorType=\"Clock\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "SmallData",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"GPU\", sensorType=\"SmallData\", sensorName!=\"GPU Memory Free (/nvidiagpu/0/smalldata/1)\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sensor_value{hardwareType=\"GPU\", sensorType=\"Throughput\"}",
     "legendFormat": "{{sensorName}}"
    }
   ]
  }
 ]
}